config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  get '/users/profile', to: 'users#profile'

  root to: 'pages#home'

  get '/tagged', to: "summaries#tagged", as: :tagged

  # get 'select2_autocompletes/:class_name'


  # resources :articles

  resources :summaries
  #   member do
  #     post
  # end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/summary.rb
class Summary < ApplicationRecord
  belongs_to :user, optional: true
  # belongs_to :taggable, polymorphic: true

  validates :article_url, presence: true

  acts_as_taggable_on :categories

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :summaries

  mount_uploader :photo, PhotoUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :photo])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/summaries_controller.rb
require 'summarize'
require 'digest'

class SummariesController < ApplicationController
  before_action :set_summary, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:show, :new, :create]
  skip_before_action :verify_authenticity_token

  # GET /summaries
  # GET /summaries.json
  def index
    @user = current_user
    @user.summaries = Summary.all
  end

  # GET /summaries/1
  # GET /summaries/1.json
  def show
    @summary = Summary.find(params[:id])
    @related_summaries = @summary.find_related_categories
  end

  # GET /summaries/new
  def new
    @user = current_user
    @summary = Summary.new
    @summary.user = @user
  end

  # GET /summaries/1/edit
  # def edit
  # end

  # POST /summaries
  # POST /summaries.json

  def create
    article_url = params.dig(:summary, :article_url)
    @summary = Summary.new(article_url: article_url)

    scraped_summary = Summarize.scrape(article_url)

    @summary.title = scraped_summary["title"]
    @summary.text = scraped_summary["text"]

    # @summary.image = scraped_summary["images"][0]["url"]

    title = scraped_summary["title"]
    text = scraped_summary["text"]

    @summary.digest = Summarize.digest(title, text)
    # @summary.article_author = Summarize.info(article_url)[:author]
    @summary.image = scraped_summary["images"][0]["url"]
    @summary.site_name = scraped_summary["siteName"]
    @summary.publish_date = Summarize.info(article_url)[:publishDate]

    @summary.tag_cloud = Summarize.keyword(article_url)

    @user = current_user
    @summary.user = @user

    respond_to do |format|
      if @summary.save
        format.json { render json: ["title": @summary.title, "text": @summary.text, "url": "https://www.hundun.io/summaries/#{@summary.id}", "image": "https://i.guim.co.uk/img/media/5e1ef6b193b314b29c8ed6b04472f51908ceb355/334_278_2639_1583/master/2639.jpg?width=1200&height=630&quality=85&auto=format&fit=crop&overlay-align=bottom%2Cleft&overlay-width=100p&overlay-base64=L2ltZy9zdGF0aWMvb3ZlcmxheXMvdGctbGl2ZS5wbmc&enable=upscale&s=beec8327bfdc6099c9feed3cc76a74ef"] }
        format.html { redirect_to @summary, notice: 'Summary was successfully created.' }
        format.js
      else
        format.html { render :new }
        format.json { render :create, status: :created, location: @summary }
      end
    end
  end

  # PATCH/PUT /summaries/1
  # PATCH/PUT /summaries/1.json
  def update
    respond_to do |format|
      if @summary.update(summary_params)
        format.html { redirect_to summaries_url, notice: 'Summary was successfully updated.' }
        format.js { head :no_content } #returning no content!!!
      else
        format.html { render :edit }
        format.json { render json: @summary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /summaries/1
  # DELETE /summaries/1.json
  def destroy
    @summary.destroy
    respond_to do |format|
      format.html { redirect_to summaries_url, notice: 'Summary was successfully removed from Dashboard' }
      format.json { head :no_content }
    end
  end

  def tagged
    # respond_to do |format|
      if params[:tag].present?
        @summaries = Summary.tagged_with(params[:tag])
        # format.html { @summaries }
        # format.json { render json: Summary.tagged_with(params[:tag]) }
        # else if params[:tag].present? && params[:format].present?
      else
        @summaries = Summary.all
        # format.json { render json: Summary.all }
      end
    # end
  end

private

    # Use callbacks to share common setup or constraints between actions.
    def set_summary
      @summary = Summary.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def summary_params
      params.require(:summary).permit(:user_id, :title, :text, :article_url, :category_list, :digest)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
def profile
  @user = current_user
end

private
  def user_params
  params.require(:user).permit(:email, :photo)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title><%= "HUNDUN Digest" %></title>
    <meta name="description" content="Extract the summary of your web articles the fastest way. Develop the multi-dimensional thinking and enjoy the different angles different sources provide you with HUNDUN.">
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= favicon_link_tag "icon128.png"%>

    <!-- Facebook -->
    <meta property="og:title" content="HUNDUN Digest" />
    <meta property="og:type" content="website" />
    <meta property="og:description" content="Extract the summary of your web articles the fastest way. Develop the multi-dimensional thinking and enjoy the different angles different sources provide you with HUNDUN." />
    <meta property="og:site_name" content="HUNDUN Digest" />
    <meta property="og:image" content="assets/meta-image.png" />

    <!-- Twitter -->
    <meta name="twitter:card" content="assets/meta-image.png">
    <meta name="twitter:image:src" content="assets/meta-image.png">
    <meta name="twitter:title" content="HUNDUN Digest">
    <meta name="twitter:description" content="Extract the summary of your web articles the fastest way. Develop the multi-dimensional thinking and enjoy the different angles different sources provide you with HUNDUN.">

    <link rel="stylesheet" type="text/css" href="loading-bar.css"/>

    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <script src="../../assets/javascripts/chrome-extension/popup.js"></script>
  </body>
</html>

app/views/pages/home.html.erb
<!-- Banner Section -->

<div class="banner">
  <div class="banner-text">
    <h1>HUNDUN | THE WORLD IN A GLIMPSE</h1>
    <p>WHY READ IT LATER | READ IT NOW</p>
    <%= link_to "Import your article", new_summary_path, class: "nav-link" %>
  </div>
</div>

<!-- What to Expect Section -->

<div class="expect">
<h1>W<span style="font-size: 25px;">HAT'S</span> <span style="font-size: 25px;"></span>H<span style="font-size: 25px;">UNDUN</span></h1>
  <div class="expect-container">
    <div class="expect-card">
      <img src="<%= image_path("newspaper-2.png") %>" style="height: 40px; width: 40px;">
      <h3>Article Summary</h3>
      <p>Know whether the article is worth reading before spending precious time reading the entire text</p>
    </div>
    <div class="expect-card">
      <img src="<%= image_path("text-lines.png") %>" style="height: 40px; width: 40px;">
      <h3>Related Articles</h3>
      <p>See related articles to understand more perspectives from alternative sources</p>
    </div>
    <div class="expect-card">
      <img src="<%= image_path("search.png") %>" style="height: 40px; width: 40px;">
      <h3>Keyword cloud</h3>
      <p>View commonly used keywords to help you evaluate article context</p>
    </div>
  </div>
</div>

<!-- Chrome Extension Section -->
<div class="chrome-extension">
<h2>Know what you want to read in just <span>1-click</span></h2>
<p class="download">Download our Chrome Extension</p>
<%= link_to image_tag("chrome.png"), "https://chrome.google.com/webstore/detail/hundun-digest/bcgbejclkendlcingllolckhcnbpnpid?authuser=1", target: '_blank'
 %>
<p>Our service is right at your hand when browsing the internet. <br>The summary of the article you read in 1-click away, provided by HUNDUN Google Chrome Extension.</p>
</div>


<!-- Catchphrase Section -->

<div class="catchphrase">
  <div class="catchphrase-content">
    <p><i class="fas fa-quote-left"></i> <em>Reading is essential for those who seek to rise above the ordinary. </em><i class="fas fa-quote-right"></i><br><span>Will it be you?</span></p>
    <%= link_to "Import your article", new_summary_path, class: "nav-link" %>
  </div>
</div>

<!-- Footer Section -->
<!-- <div class="footer-descripition"><p>Share Hundun & Get in touch with us</p></div> -->
<div class="footer">
  <ul class ="list-inline">
    <li><a href="http://www.facebook.com/share.php?u=https://www.hundun.io" target="_blank"><i class="fab fa-facebook-f"></i></a></li>
    <li><a href="https://github.com/manjiej/hundun" target="_blank"><i class="fab fa-github"></i></a></li>
    <li><a href="https://twitter.com/intent/tweet?text=Hundun%20Digest%20%E2%80%94%20A%20tool%20to%20get%20a%20good%20summary%20of%20a%20article%20quickly%20https%3A//www.hundun.io" target="_blank"><i class="fab fa-twitter"></i></a></li>
    <li><a href="https://www.instagram.com/mkenziemj/" target="_blank"><i class="fab fa-instagram"></i></a></li>
  </ul>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-lewagon fixed-top" style= "padding: 0 15px">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "icon128.png", style: "height: 57px; width: 57px; margin-left: 10px;" %>
    <span>HUNDUN</span>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
      <div class="navbar-active" style= "font-family: 'Lato'">
        <li class="nav-item active">

          <%= link_to "HOME", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "DASHBOARD", summaries_path, class: "nav-link" %>
        </li>
      </div>
        <li class="nav-item-dropdown">
          <%= image_tag current_user.photo_url || "https://cn.bing.com/th?id=OIP.vFYAYMSIurPqs1eV7L0GpwHaHa&pid=Api&rs=1", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown" style="font-family: 'Lato'; margin-top: -1px;">
            <%= link_to "Update my profile", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item" style= "font-family: 'Lato'">
          <%= link_to "HOME", root_path, class: "btn-home", style: "padding: 40px;"%>
          <%= link_to "LOGIN", new_user_session_path, class: "btn-login", style: "padding: 40px;" %>
          <%= link_to "SIGN UP", new_user_registration_path, class: "btn-signup", style: "padding: 40px;" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

<!-- <script>
  const logo = document.getElementById('logo')
    logo.addEventListener('mouseover', (event) => {
      console.log(event)
    })

</script> -->

app/views/summaries/_form.html.erb
  <%= simple_form_for(@summary, :html => { :onsubmit => "loading()" }) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs import-input">
      <%= f.input :article_url, placeholder: "Paste your article url here" %>
    </div>
    <div class="import-bottom">
      <div class="form-actions import-btn">
        <%= f.button :submit, "Digest" %>
      </div>
      <div id="loader">
      </div>
    </div>
  <% end %>

  <script type="text/javascript">

    loading = () => {
    const container = document.getElementById("loader");

    container.innerHTML = "<img src='https://image.noelshack.com/fichiers/2019/51/4/1576738253-spin-2.gif'>"
    }

  </script>

app/views/summaries/_tags.html.erb
<div class="tags-input">

  <%= simple_form_for(summary, remote: true) do |f| %>
    <%= f.hidden_field :category_list %>
    <%= select_tag "category", options_from_collection_for_select(
      ActsAsTaggableOn::Tag.all.map { |tag| tag }.sort_by { |tag| tag.name }, :name, :name), class: 'select2', multiple: "multiple" ,style: "width: 40%; margin: 0 auto;"%>
      <div class="add-btn">

    <%= f.button :submit, "Add", :class => "btn-link", :id => "submit-tag"%>
      </div>
  <% end %>

</div>

app/views/summaries/index.html.erb
<div class="dashboard">

  <div class="dashboard-title">
    <h1>My Digests</h1>
  </div>

  <div class="category" id="cat-tag">
    <% category_list = ['Business', 'Culture', 'Economics', 'Education', 'Environment', 'Politics', 'Society', 'Science', 'Technology'] %>
    <% category_list.each do |cat| %>
      <%= link_to cat, tagged_path(tag: cat), class:"btn btn-outline-dark" %>
    <% end %>
  </div>

  <div class="dashboard-container">
  <% @user.summaries.order(id: :desc).each do |summary| %>
    <div class="dashboard-card">
      <div class="dashboard-tag">
        <p><% summary.category_list.each do |tag| %>
          <%= link_to tag, tagged_path(tag: tag) %>
        <% end %></p>
      </div>
      <div class="dashboard-text">
        <h3><%= link_to summary.title, summary %></h3>
        <p><%= summary.digest %></p>
        <div class="ellipsis">
          <p><%=link_to "...", summary %></p>
        </div>
      </div>
        <div class="dashboard-site-name">
          <p><i class="far fa-newspaper"></i> <%= summary.site_name %></p>
        </div>
      <div class="stick-bottom">
        <div class="dashboard-links">
          <p><%= link_to 'Delete', summary, method: :delete, data: { confirm: 'Are you sure to delete it from your dashboard?' } %></p>
        </div>
      </div>
    </div>
      <% end %>
  </div>

    <br>
  <div class="dashboard-import">
    <%= link_to 'Import another article', new_summary_path %>
  </div>
</div>

<!-- <script>
  const catTags = document.querySelectorAll('#cat-tag p')

  catTags.forEach((cat) => {

    cat.addEventListener('click', (event) => {
      // 获取节点，判断是否有class；有，加tag；没有，移除tag


    // console.log(event.target["innerText"])
    fetch(`http://localhost:3000/tagged.json?tag=${event.target["innerText"]}`)
      .then(response => response.json())
      .then((data) => {
        console.log(data)
        const tags = data.length
            document.querySelectorAll('.dashboard-card').forEach((e) => {
              e.remove()
            })
            data.forEach((ele) => {
              document.querySelector('.dashboard-container').insertAdjacentHTML(
               "beforeend",
               '<div class="dashboard-card"><div class="dashboard-tag"><p><a href="/tagged?tag='+event.target["innerText"]+'">'+ele.category_list+'</a></p></div><div class="dashboard-text"><h3><a href="/summaries/10">'+ ele.title+'</a></h3><p>'+ ele.digest+'</p><div class="ellipsis"><p><a href="/summaries/10">...</a></p></div></div><div class="dashboard-site-name"><p><i class="far fa-newspaper"></i> Fox News</p></div><div class="stick-bottom"><div class="dashboard-links"><p><a data-confirm="Are you sure to delete it from your dashboard?" rel="nofollow" data-method="delete" href="/summaries/10">Delete</a></p></div></div></div>');
            })

        })
      })
    })

</script>
 -->


<!-- <script>
  $.ajax({
    type: "POST",
    url: "http://localhost:3000/summaries",
    data: { id1: id, comment1: comment },
    success: function(data) {
        $("#feedback").html(data);
        $('#feedback').fadeIn('slow', function() {
            $('#feedback').fadeOut(4000);
            window.location = "comment.php";
        }
 });
</script> -->

app/views/summaries/new.html.erb
<div class="import-container" id="import-container">

  <div class="import-content" id="import-content">
    <div class="import-title">
      <h3>Extract the summary of your web articles the fastest way</h3>
      <p>Go explore!</p>
    </div>

    <div class="container">

      <%= @summary[:article_url] %>

      <%= render 'form', summary: @summary %>

      <%#= link_to 'Back', summaries_path %>

    </div>

  </div>
</div>

app/views/summaries/popup.html.erb
popup.html.erb

<%= anything here %>

app/views/summaries/show.html.erb
<div class="summarized-title">
  <h1><strong><%= @summary.title %></strong></h1>
</div>

<div class="summarized-info">
  <span><%= @summary.site_name %></span> | <span><%= Date.parse(@summary.publish_date).strftime("%A, %b %d") %></span> | <span>  Share on
  <a title="Share on facebook" class="facebook" target="_blank" onclick="return fbs_click()" href="http://www.facebook.com/share.php?u=https://www.hundun.io/summaries/<%= @summary.id %>" rel="nofollow"><i class="fab fa-facebook-f"></i></a>
  <a class="twitter" title="Share on twitter" target="_blank" data-lang="en" data-via="your_screen_name" data-url="https://www.hundun.io" href="https://www.hundun.io"><i class="fab fa-twitter"></i></a>
  <a class="email" title="Share by e-mail" href="mailto:?subject=Tool: Hundun(Digest articles quickly)&amp;body=Hundun Digest, by students%0A
  from Le wagon%0A
  https://www.hundun.io"><i class="far fa-envelope"></i></a></span>


  <a href="https://twitter.com/intent/tweet?text=Hundun%20Digest%20%E2%80%94%20A%20tool%20to%20get%20a%20good%20summary%20of%20a%20article%20quickly%20https%3A//www.hundun.io" target="_blank" ><img src="https://assets.website-files.com/5cfbc938982a74a06bedeb1a/5d276e132836ca87b8ce302d_icon-Social-TW.png" width="22" alt="" class="icon-social"></a>
</div>

<div class="summarized-text">
  <p><%= @summary.digest %></p>
</div>

<div class="summarized-url">
  <a href="<%= @summary.article_url %>" target="_blank">Link to Full Article</a>
</div>

<!-- <div class="summarized-img">
  <img src="assets/elcarito-MHNjEBeLTgw-unsplash.jpg">
  <img src="<%= @summary.image %>" alt="banner image">
</div> -->

<script src="https://www.amcharts.com/lib/4/core.js"></script>
<script src="https://www.amcharts.com/lib/4/charts.js"></script>
<script src="https://www.amcharts.com/lib/4/plugins/wordCloud.js"></script>
<script src="https://www.amcharts.com/lib/4/themes/moonrisekingdom.js"></script>
<script src="https://www.amcharts.com/lib/4/themes/animated.js"></script>


  <!-- Put Chart Div in bg-img -->
  <!-- Make bg-img full width and give it a height -->
  <!-- Make bg-img display: flex; justify-content: center; align-items: center; -->
  <!-- Make bg-img background: url('your-url-here'); -->


<div class="bg-img">
  <div id="chartdiv">
    <script>
      // Themes begin
      am4core.useTheme(am4themes_animated);

      // Themes end
      var chart = am4core.create("chartdiv", am4plugins_wordCloud.WordCloud);
      chart.fontFamily = "Lato";
      var series = chart.series.push(new am4plugins_wordCloud.WordCloudSeries());
      series.randomness = 0;
      series.rotationThreshold = 0.5;

      series.data = <%= raw @summary.tag_cloud %>;

      series.dataFields.word = "label";
      series.dataFields.value = "count";

      series.heatRules.push({
       "target": series.labels.template,
       "property": "fill",
       "min": am4core.color("#4f8fc6"),
       "max": am4core.color("#354d62"),
       "dataField": "value"
      });

      series.labels.template.url = "https://en.wikipedia.org/wiki/{word}";
      series.labels.template.urlTarget = "_blank";
      series.labels.template.tooltipText = "{word}: {value}";

      var hoverState = series.labels.template.states.create("hover");
      hoverState.properties.fill = am4core.color("#FC7978");

      var subtitle = chart.titles.create();
      subtitle.text = "(Click to open Wikipedia)";

      var title = chart.titles.create();
      title.text = "Most Popular Tags From Your Article";
      title.fontSize = 20;
      title.fontWeight = "800";
      title.color= am4core.color("#FC7978");
    </script>
  </div>
</div>

<div class="related-sum-container">
<h3>Other users also read those articles</h3>

  <div class="related-sum-articles">
      <% @related_summaries.each do |r| %>
        <p><%= link_to r.title, summary_path(id: r.id) %></p>
      <% end %>
  </div>
  <br>
  <p class = "tag" style="text-align: center; font-family: 'Lato'; font-size: 20px;">
    Find more about...<% @summary.category_list.each do |tag| %>
      <strong><%= link_to tag, tagged_path(tag: tag) %></strong>
    <% end %>
  </p>
</div>

<%= render 'tags', summary: @summary %>

<div class="related-sum-links">
  <%= link_to 'Go to Dashboard', summaries_path(@summary) %>
  <%= link_to 'Back', new_summary_path %>
</div>

app/views/summaries/tagged.html.erb
<div class="tagged">
  <div class="tagged-title">
    <h1>#<%= params[:tag]%></h1>
  </div>

  <div class="tagged-container">

    <% @summaries.each do |summary| %>
    <div class="tagged-card">
      <div class="tagged-tag">
        <p><% summary.category_list.each do |tag| %>
        <%= link_to tag, tagged_path(tag: tag) %>
      <% end %></p>
      </div>
      <div class="tagged-text">
        <h3><%= link_to summary.title, summary %></h3>
        <p><%= summary.digest %></p>
        <div class="ellipsis">
          <p>...</p>
        </div>
      </div>
        <div class="tagged-site-name">
          <p><i class="far fa-newspaper"></i> CNN</p>
        </div>
        <div class="stick-bottom">
        <div class="tagged-delete">
          <p><%= link_to 'Delete', summary, method: :delete, data: { confirm: 'Are you sure to delete it from your dashboard?' } %></p>
        </div>
      </div>
    </div>
    <% end %>

  </div>
  <div class="tagged-links">
    <%= link_to "Go Back to all Summaries", summaries_path %>
  </div>

</div>

app/views/users/profile.html.erb
<h1 class="profile-page">My Profile Page</h1>

<div class="profile-container">
  <div class="profile-infos">

    <%= cl_image_tag current_user.photo, height: 300, width: 400, crop: :fill %>
    <p>Email: <%= current_user.email %></p>

  </div>
</div>